# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.angusgordon.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Grid life
  avatar:
  gravatar: # Email MD5 hash
  description: "Angus Gordon's personal blog" # used by search engines
  
  # Header and footer text
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: true
  email_address: angus@angusgordon.com
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: 
  google_plus: 
  instagram: 
  linkedin:
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # Full URL
  steam: 
  tumblr: 
  twitter: "angusgmelb"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: UA-60775800-1
  disqus_shortname:
  katex: true # Enable if using math markup 
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "More"
  
  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
encoding: UTF-8